name: Documentation update 📝
description: Tell us if you have any idea of features 🔥💭
title: "Doc: "
labels: [ "documentation" ]
body:

  - type: textarea
    id: doc-details
    attributes:
      label: What do you want to add or update 📝
      description: Type here, what you want to add or update in the documentation.
      placeholder: Use markdown if you want.
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Contribution terms 📝
      description: By submitting this issue, you agree to follow our [Contributing guide](https://github.com/Tykok/PokeAPI-Kotlin/blob/main/CONTRIBUTING.md)
      options:
        - label: I agree to follow this project's Contributing guide
          required: true
