name: 'Auto Assign PR to Author'
on:
  pull_request:
    types: [ opened ]

permissions:
  contents: read

jobs:
  add-reviews:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.1
