name: Release PokeAPI

env:
  OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Publish PokeAPI
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Get project version
        run: |
          PROJECT_VERSION=$(sh gradlew getProjectVersion | grep VERSION | cut -d ":" -f 2 | sed 's/ //g'   )
          echo "### Project version $PROJECT_VERSION" >> $GITHUB_STEP_SUMMARY
          echo "PROJECT_VERSION=$PROJECT_VERSION" >> ${GITHUB_ENV}

      #- name: Publish to GitHub Packages
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: pokeapi
      #    path: '${{ github.workspace }}/build/libs/pokeapi-${{ env.PROJECT_VERSION }}.jar'
      - name: Build Changelog
        uses: mikepenz/release-changelog-builder-action@v4.0.0-rc09
        if: ${{ success() }}
        id: build_changelog
        with:
          configuration: "${{ github.workspace }}/.github/changelog-builder.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        if: ${{ success() }}
        id: create_release
        uses: ncipollo/release-action@v1.13.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ env.PROJECT_VERSION }}
          body: ${{steps.build_changelog.outputs.changelog}}
          artifacts: "${{ github.workspace }}/build/libs/pokeapi-${{ env.PROJECT_VERSION }}.jar"
          makeLatest: "latest"

  publish:
    name: Publish PokeAPI
    runs-on: ubuntu-latest
    needs:
      - release

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Publish PokeAPI
        run: sh gradlew build

      - name: Publish PokeAPI
        if: ${{ success() }}
        run: sh gradlew publish
