name: ktlint

on:
  pull_request:
    paths:
      - .github/workflows/*
      - 'src/**/*.kt'
      - '**.kts'

jobs:
  ktlint-check:
    name: Ktlint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check code style with ktlint
        run: |
          sh gradlew ktlinCheck
