name: Publish PokeAPI

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish PokeAPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Publish PokeAPI
        run: ./gradlew publish

      - name: Get project version
        run: gradle getProjectVersion -q

      - name: Publish to GitHub Packages
        uses: actions/upload-artifact@v3
        with:
          name: pokeapi
          path: 'build/libs/pokeapi-${{ steps.get-project-version.outputs.version }}.jar'
