name: Publish PokeAPI

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish PokeAPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Publish PokeAPI
        run: ./gradlew publish
